version: "3.6"

networks:
  default:
    external:
      name: network

services:
  tg-statlog-bot:
    container_name: tg-statlog-bot
    build:
      context: .
      dockerfile: ./build/nodejs/Dockerfile
    restart: "always"
    image: registry.gitlab.com/aliasgame/tg-statlog-bot:node_14
    env_file: ./build/.env.list
